Repository BFARIAAL/api-pdc-backend, pull requests merged in 2023-09, with the labels that each got.

#4 Implemented DB
  data/db.sql
  src/main/java/com/jlr/ttl/poc/loadmanager/models/Vehicle.java
  src/main/java/com/jlr/ttl/poc/loadmanager/services/VehicleService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: enhancement

#10 Added the missing imports and the crossorigin annotations
  src/main/java/com/jlr/ttl/poc/loadmanager/controllers/LoadController.java
  src/main/java/com/jlr/ttl/poc/loadmanager/controllers/LocationController.java
  src/main/java/com/jlr/ttl/poc/loadmanager/controllers/VehicleController.java
Labels: bug

#16 New Users DB Table
  data/db.sql
Labels: feature
